
// This file has been generated by the GUI designer. Do not modify.
namespace VideoAggregator
{
	public partial class ShowResultsWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VideoAggregator.ShowResultsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VideoAggregator.ShowResultsWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
