
// This file has been generated by the GUI designer. Do not modify.
namespace VideoAggregator
{
	public partial class EmbeddedWidget
	{
		private global::Gtk.VBox vbox;
		
		private global::Gtk.ScrolledWindow scrolledwindow;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VideoAggregator.EmbeddedWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VideoAggregator.EmbeddedWidget";
			// Container child VideoAggregator.EmbeddedWidget.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.scrolledwindow = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow.CanFocus = true;
			this.scrolledwindow.Name = "scrolledwindow";
			this.scrolledwindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox.Add (this.scrolledwindow);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox [this.scrolledwindow]));
			w1.PackType = ((global::Gtk.PackType)(1));
			w1.Position = 0;
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
